---
output:
  pdf_document:
    latex_engine: xelatex
    keep_tex: false
    number_section: false
    template: input/template.tex
indent: true
---

```{r setup, echo  = FALSE, include = FALSE}
library(knitr)
if(!require(estatsr)) devtools::install_github("estatsej/estatsr")
Sys.setlocale("LC_TIME", "pt_BR.UTF-8") # Unix
#Sys.setlocale("LC_TIME", "portuguese") # Windows
```

```{r, include = FALSE}
titulo <- "titulo"
gerente <- "Eduardo"
assessores <- c("Ellen", "Larissa", "Samuel")

ret_ <- glue::glue("\\begin{titlepage}
\\begin{center}

\\vspace*{4.5cm}

\\begin{Large}
\\textbf{Relatório Final} \\\\ \n
\\end{Large}

\\begin{LARGE}
\\textbf{`{titulo}`} \\\\ \n
\\end{LARGE}

\\end{center}

\\vspace*{3cm}

\\flushleft{
  \\begin{large}
  \\textbf{Responsáveis:} \\\\ \n
  \\end{large}
  Gerente: `{gerente}` \\\\\\ \n
  Assessores:
  `{paste(assessores, '', collapse = '\\\\\\\\ \n')}`
}

\\vfill

\\begin{center}
Maringá \\\\ \n
\\today
\\end{center}
\\end{titlepage}",
.open = "`{", .close = "}`")


```

`r ret_`
